language: python

python:
  - "3.5"
  - "3.6"
  - "3.7-dev"

sudo: false

env:
  - DJANGO=1.11
  - DJANGO=2.0
  - DJANGO=2.1
  - DJANGO=master

matrix:
  fast_finish: true
  exclude:
    - python: "3.7-dev"
      env: DJANGO=1.11

  allow_failures:
    - env: DJANGO=master

install: pip install tox tox-travis codecov

script: tox

after_success:
  - codecov -e TOXENV,DJANGO

notifications:
  email: false
